version: "3.9"

services:

  mongodb:
    image: mongo:6.0.13
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - 27017:27017
    restart: on-failure
    networks:
      - dev-net

  # use badger as storage
  jaeger-all-in-one:
    image: jaegertracing/all-in-one:1.30
    container_name: jaeger-all-in-one
    environment:
      - SPAN_STORAGE_TYPE=badger
      - BADGER_EPHEMERAL=false
      - BADGER_DIRECTORY_VALUE=/badger/data
      - BADGER_DIRECTORY_KEY=/badger/key
    ports:
      - 16686:16686
    volumes:
      - ~/data/badger:/badger
    restart: always
    networks:
      - dev-net

  # with elastic 
  
  # jaeger-elasticsearch:
  #   image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
  #   networks:
  #     - dev-net
  #   ports:
  #     - "9200:9200"
  #     - "9300:9300"
  #   restart: on-failure
  #   environment:
  #     - cluster.name=jaeger-cluster
  #     - discovery.type=single-node
  #     - http.host=0.0.0.0
  #     - transport.host=127.0.0.1
  #     - ES_JAVA_OPTS=-Xms512m -Xmx512m
  #     - xpack.security.enabled=false
  #   volumes:
  #     - esdata:/usr/share/elasticsearch/data

  # jaeger-collector:
  #   image: jaegertracing/jaeger-collector:1.53
  #   ports:
  #     - "14269:14269"
  #     - "14268:14268"
  #     - "14267:14267"
  #     - "14250:14250"
  #     - "9411:9411"
  #   networks:
  #     - dev-net
  #   restart: on-failure
  #   environment:
  #     - SPAN_STORAGE_TYPE=elasticsearch
  #   command: [
  #       "--es.server-urls=http://elasticsearch:9200",
  #       "--es.num-shards=1",
  #       "--es.num-replicas=0",
  #       "--log-level=error",
  #     ]
  #   depends_on:
  #     - jaeger-elasticsearch

  # jaeger-agent:
  #   image: jaegertracing/jaeger-agent:1.53
  #   hostname: jaeger-agent
  #   command: ["--collector.host-port=jaeger-collector:14267"]
  #   ports:
  #     - "5775:5775/udp"
  #     - "6831:6831/udp"
  #     - "6832:6832/udp"
  #     - "5778:5778"
  #   networks:
  #     - dev-net
  #   restart: on-failure
  #   environment:
  #     - SPAN_STORAGE_TYPE=elasticsearch
  #   depends_on:
  #     - jaeger-collector

  # jaeger-query:
  #   image: jaegertracing/jaeger-query:1.53
  #   environment:
  #     - SPAN_STORAGE_TYPE=elasticsearch
  #     - ES_SERVER_URLS=localhost:9200
  #     # - no_proxy=localhost
  #   ports:
  #     - "16686:16686"
  #     - "16687:16687"
  #     - "16685:16685"
  #   networks:
  #     - dev-net
  #   restart: on-failure
  #   command: [
  #       "--es.server-urls=http://elasticsearch:9200",
  #       "--span-storage.type=elasticsearch",
  #       "--log-level=debug",
  #     ]
  #   depends_on:
  #     - jaeger-agent

volumes:
  esdata:
    driver: local

networks:
  dev-net:
    driver: bridge
